# Computing on data

In [1]:
A = [1 2 ; 3 4; 5 6]

A =

   1   2
   3   4
   5   6



In [2]:
B = [11 12; 13 14; 15 16]

B =

   11   12
   13   14
   15   16



In [3]:
C = [1 1; 2 2]

C =

   1   1
   2   2



In [4]:
A * C

ans =

    5    5
   11   11
   17   17



In [5]:
A .* B                 # element multiplication

ans =

   11   24
   39   56
   75   96



In [6]:
A .^2                   

ans =

    1    4
    9   16
   25   36



In [7]:
v = [1; 2; 3]

v =

   1
   2
   3



In [8]:
1 ./ v

ans =

   1.00000
   0.50000
   0.33333



In [9]:
log(v)

ans =

   0.00000
   0.69315
   1.09861



In [10]:
exp(v)

ans =

    2.7183
    7.3891
   20.0855



In [11]:
abs([-1; -2; 3])

ans =

   1
   2
   3



In [12]:
-v

ans =

  -1
  -2
  -3



In [13]:
v + ones(length(v), 1)

ans =

   2
   3
   4



In [14]:
v + 1

ans =

   2
   3
   4



In [15]:
A'                        # transpose

ans =

   1   3   5
   2   4   6



In [16]:
(A')'

ans =

   1   2
   3   4
   5   6



In [17]:
max(v)

ans =  3


In [18]:
[val, ind] = max(v)

val =  3
ind =  3


In [19]:
max(A)              # return each column max value

ans =

   5   6



In [20]:
a = randn(1, 4)

a =

  -1.114876  -1.108318  -0.149881   0.085866



In [21]:
a < 0.5

ans =

  1  1  1  1



In [22]:
find(a < 0.5)

ans =

   1   2   3   4



In [23]:
A = magic(3)          # create n * n square matrix

A =

   8   1   6
   3   5   7
   4   9   2



In [24]:
[r, c] = find(A > 7)             # 将查找的值返回row， col index到两个列变量中

r =

   1
   3

c =

   1
   2



In [25]:
A(r(1), c(1))

ans =  8


In [26]:
a = rand(3)

a =

   0.255515   0.507500   0.143037
   0.933329   0.538787   0.722887
   0.800887   0.772309   0.080873



In [27]:
sum(a)                  # sum along column

ans =

   1.98973   1.81860   0.94680



In [28]:
prod(a)

ans =

   0.1909950   0.2111762   0.0083622



In [29]:
ceil(a)

ans =

   1   1   1
   1   1   1
   1   1   1



In [30]:
floor(a)

ans =

   0   0   0
   0   0   0
   0   0   0



In [31]:
max(rand(3), rand(3))           # 取两个矩阵中最大的元素

ans =

   0.41433   0.44225   0.94678
   0.99064   0.63851   0.18567
   0.84672   0.89340   0.91449



In [32]:
A

A =

   8   1   6
   3   5   7
   4   9   2



In [33]:
max(A, [], 1)

ans =

   8   9   7



In [34]:
max(A)

ans =

   8   9   7



In [35]:
max(A, [], 2)

ans =

   8
   7
   9



In [36]:
max(A(:))

ans =  9


In [37]:
A = magic(9)

A =

   47   58   69   80    1   12   23   34   45
   57   68   79    9   11   22   33   44   46
   67   78    8   10   21   32   43   54   56
   77    7   18   20   31   42   53   55   66
    6   17   19   30   41   52   63   65   76
   16   27   29   40   51   62   64   75    5
   26   28   39   50   61   72   74    4   15
   36   38   49   60   71   73    3   14   25
   37   48   59   70   81    2   13   24   35



In [38]:
sum(A, 1)

ans =

   369   369   369   369   369   369   369   369   369



In [39]:
sum(A, 2)          # sum each row

ans =

   369
   369
   369
   369
   369
   369
   369
   369
   369



In [40]:
eye(9)

ans =

Diagonal Matrix

   1   0   0   0   0   0   0   0   0
   0   1   0   0   0   0   0   0   0
   0   0   1   0   0   0   0   0   0
   0   0   0   1   0   0   0   0   0
   0   0   0   0   1   0   0   0   0
   0   0   0   0   0   1   0   0   0
   0   0   0   0   0   0   1   0   0
   0   0   0   0   0   0   0   1   0
   0   0   0   0   0   0   0   0   1



In [41]:
B = A .* eye(9)

B =

   47    0    0    0    0    0    0    0    0
    0   68    0    0    0    0    0    0    0
    0    0    8    0    0    0    0    0    0
    0    0    0   20    0    0    0    0    0
    0    0    0    0   41    0    0    0    0
    0    0    0    0    0   62    0    0    0
    0    0    0    0    0    0   74    0    0
    0    0    0    0    0    0    0   14    0
    0    0    0    0    0    0    0    0   35



In [42]:
sum(B(:))

ans =  369


In [43]:
flipud(eye(9))

ans =

Permutation Matrix

   0   0   0   0   0   0   0   0   1
   0   0   0   0   0   0   0   1   0
   0   0   0   0   0   0   1   0   0
   0   0   0   0   0   1   0   0   0
   0   0   0   0   1   0   0   0   0
   0   0   0   1   0   0   0   0   0
   0   0   1   0   0   0   0   0   0
   0   1   0   0   0   0   0   0   0
   1   0   0   0   0   0   0   0   0



In [44]:
sum(sum(A .* flipud(eye(9))))

ans =  369


In [45]:
AI = pinv(A)

AI =

 Columns 1 through 6:

  4.5353e-004  -1.2230e-003  1.6729e-003  1.2647e-002  -1.2062e-002  3.1805e-004
  3.0111e-004  3.0111e-004  1.2801e-002  -1.2199e-002  3.0111e-004  -1.0878e-003
  -1.0706e-003  1.4019e-002  -1.2045e-002  3.0091e-004  4.5374e-004  1.4870e-004
  1.2647e-002  -1.2045e-002  3.0132e-004  3.0300e-004  -1.0725e-003  1.6729e-003
  -1.0810e-002  3.0111e-004  3.0111e-004  3.0111e-004  3.0111e-004  3.0111e-004
  2.8418e-004  4.7047e-004  1.4870e-004  -1.0706e-003  1.6747e-003  2.9923e-004
  3.0300e-004  2.8230e-004  3.1805e-004  4.5353e-004  1.4849e-004  3.0132e-004
  3.0111e-004  3.0111e-004  -1.0878e-003  1.6900e-003  3.0111e-004  1.2801e-002
  3.0091e-004  3.0320e-004  2.9923e-004  2.8418e-004  1.2664e-002  -1.2045e-002

 Columns 7 through 9:

  3.0300e-004  2.9902e-004  3.0132e-004
  1.6900e-003  3.0111e-004  3.0111e-004
  2.8418e-004  3.1993e-004  2.9923e-004
  4.5353e-004  1.3176e-004  3.1805e-004
  3.0111e-004  3.0111e-004  1.1412e-002
  3.0091e-004  1.2647e-0

In [46]:
AI * A

ans =

 Columns 1 through 6:

  1.0000e+000  -2.5674e-016  -3.5692e-016  -1.1015e-016  -6.4618e-017  -1.3661e-016
  -2.2248e-016  1.0000e+000  2.3983e-016  -1.4832e-016  1.6090e-016  -1.4669e-016
  3.2960e-017  -7.2685e-016  1.0000e+000  -6.9389e-017  -4.5103e-017  1.6079e-016
  -3.9703e-016  -1.0061e-016  -6.0737e-016  1.0000e+000  -1.1861e-016  9.3458e-017
  1.6306e-016  -4.9960e-016  3.4694e-018  -4.9266e-016  1.0000e+000  -3.9205e-016
  1.7521e-016  3.0531e-016  2.1337e-016  5.6552e-016  3.6256e-016  1.0000e+000
  -3.3827e-017  -1.6653e-016  1.7954e-016  4.8399e-016  -3.4955e-016  -1.8388e-016
  3.1008e-016  -4.5103e-017  3.0748e-016  4.4843e-016  5.8243e-016  2.2714e-016
  -5.6758e-017  -1.7260e-016  5.8493e-017  -3.1333e-017  -6.3464e-016  -5.2248e-016

 Columns 7 through 9:

  -3.4998e-016  4.7705e-017  2.2204e-016
  -2.1120e-016  1.9082e-016  8.3267e-017
  1.5005e-016  -3.7036e-016  3.3307e-016
  -7.5894e-018  2.3939e-016  -4.8572e-017
  1.6306e-016  -2.7756e-017  -4.0246e-016


In [47]:
A * AI == 0

ans =

  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0

